{
 "title": "MongoDB",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "mongodb_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total commands executed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "mongodb_ss_metrics_commands_dbStats_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "mongodb_dbstats_dataSize", "legendFormat": "__auto" }
   ]
  }
 ]
}